FROM python:3.7-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends git \
 && apt-get purge -y --auto-remove \
 && rm -rf /var/lib/apt/lists/*
RUN pip install mlflow pymysql

USER root
