raw_data: "data/raw_data/heart.csv"
experiment_name: "rf"
random_state: 1
label: "target"
splitting_params:
  val_size: 0.3
  stratify: false
train_params:
  model_type: "RandomForestClassifier"
  mean_alpha: 20
  imput_strategy: "median"
feature_params:
  cat_cols:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  real_cols:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
