apiVersion: v1
kind: Pod
metadata:
  name: online-inference-ml-resources
  labels:
    app: online-inference-ml-resources
spec:
  containers:
    - image: imdxd/webserver:v1
      name: online-inference-ml-resources
      ports:
        - containerPort: 4000
      resources:
        requests:
          memory: "1Gi"
          cpu: "250m"
        limits:
          memory: "4Gi"
          cpu: "500m"
