feature_params:
  cat_cols:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  real_cols:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"